version: '3.8'
services:
  db_user_auth:
    image: citusdata/citus:10.2
    container_name: db_user_auth
    environment:
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: user_auth_db
      POSTGRES_USER: user_auth
    volumes:
      - user_auth_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db_user_profile:
    image: citusdata/citus:10.2
    container_name: db_user_profile
    environment:
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: user_profile_db
      POSTGRES_USER: user_profile
    volumes:
      - user_profile_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  db_user_activity:
    image: citusdata/citus:10.2
    container_name: db_user_activity
    environment:
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: user_activity_db
      POSTGRES_USER: user_activity
    volumes:
      - user_activity_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  db_user_payment:
    image: citusdata/citus:10.2
    container_name: db_user_payment
    environment:
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: user_payment_db
      POSTGRES_USER: user_payment
    volumes:
      - user_payment_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  db_europe:
    image: citusdata/citus:10.2
    container_name: db_europe
    environment:
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: europe_db
      POSTGRES_USER: region_user
    volumes:
      - europe_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    depends_on:
      - db_user

  db_america:
    image: citusdata/citus:10.2
    container_name: db_america
    environment:
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: america_db
      POSTGRES_USER: region_user
    volumes:
      - america_data:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    depends_on:
      - db_user

  db_asia:
    image: citusdata/citus:10.2
    container_name: db_asia
    environment:
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: asia_db
      POSTGRES_USER: region_user
    volumes:
      - asia_data:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    depends_on:
      - db_user

  db_africa:
    image: citusdata/citus:10.2
    container_name: db_africa
    environment:
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: africa_db
      POSTGRES_USER: region_user
    volumes:
      - africa_data:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    depends_on:
      - db_user

volumes:
  user_data:
  user_extra_data:
  europe_data:
  america_data:
  asia_data:
  africa_data:
